services:
  - type: web
    name: n8n
    env: docker
    dockerfilePath: ./Dockerfile
    region: singapore
    plan: standard
    branch: main
    numInstances: 1
    healthCheckPath: /healthz

    # Persistent storage for credentials, settings, etc.
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 5

    envVars:
      # ---- Database wiring (managed Postgres below) ----
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-db
          property: database
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-db
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_SCHEMA
        value: public

      # ---- Required secrets / basics ----
      - key: N8N_ENCRYPTION_KEY
        generateValue: true
      - key: N8N_LOG_LEVEL
        value: info
      - key: TZ
        value: Asia/Ho_Chi_Minh
      - key: GENERIC_TIMEZONE
        value: Asia/Ho_Chi_Minh
      - key: N8N_SECURE_COOKIE
        value: "true"
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"

      # ---- Optional basic auth for the UI ----
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        generateValue: true

      # ---- Set these AFTER first deploy & custom domain is attached ----
      # - key: N8N_HOST
      #   value: n8n.yourdomain.com
      # - key: WEBHOOK_URL
      #   value: https://n8n.yourdomain.com
      # - key: N8N_EDITOR_BASE_URL
      #   value: https://n8n.yourdomain.com
      # - key: N8N_PUBLIC_API_BASE_URL
      #   value: https://n8n.yourdomain.com

databases:
  - name: n8n-db
    plan: basic-1gb
    region: singapore
